### ISSUE TITLE
Meta: Reduce bundle size

### ISSUE THREAD

**Issue by LogvinovLeon** [0xProject/website#92]
- [ ] Tree shake lodash
- [ ]  Merge 0x.js perf fixes
- [ ]  Remove unused languages from highlight.js
- [ ]  Make sure we only bundle single version of web3 (truffle-contract)
